Update gpt-commit-summarizer.yml

diff --git a/.github/workflows/gpt-commit-summarizer.yml b/.github/workflows/gpt-commit-summarizer.yml
--- a/.github/workflows/gpt-commit-summarizer.yml
+++ b/.github/workflows/gpt-commit-summarizer.yml
@@ -1,18 +1,26 @@
 name: GPT Commits summarizer
-# Summary: This action will write a comment about every commit in a pull request, as well as generate a summary for every file that was modified and add it to the review page, compile a PR summary from all commit summaries and file diff summaries, and delete outdated code review comments
 
 on:
   pull_request:
     types: [opened, synchronize]
-  workflow_dispatch:
-  
+
 jobs:
   summarize:
     runs-on: ubuntu-latest
-    permissions: write-all  # Some repositories need this line
-
+    permissions:
+      pull-requests: write
+      contents: read
+    
     steps:
       - uses: KanHarI/gpt-commit-summarizer@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+        continue-on-error: true
+        id: summarizer
+        
+      - name: Check summarizer status
+        if: steps.summarizer.outcome != 'success'
+        run: |
+          echo "Summarizer failed to run"
+          exit 1
